name: TerraformwithAWS
run-name: infra on AWS

on: 
  workflow_dispatch:

jobs:
  firstjobtocheckconnection:
    name: First Job to Check AWS Connection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AWS_SECRET.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ AWS_SECRET.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if needed

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
